# Project information
site_name: Python Grammer
site_url: https://kzrashi.github.io/python-grammer/
site_author: kzrashi
site_description: >-
  This site illustrates grammer of python programing language for beginners.

# Repository
## GitのURL
repo_url: https://github.com/kzrashi/python-grammer
## 表示文字列
repo_name: kzrashi/python-grammer

# Configuration
theme:
  name: material
  font:
    text: "UD デジタル 教科書体 NK-R,ヒラギノ角ゴシック"   #Regular font(通常フォント)
    code: "UDデジタル教科書体N-R"       #Monospaced font(等幅フォント)
  language: ja
  # 左上のアイコン
  logo: assets/python_94570.svg
  icon:
    # Gitリポジトリエリアのアイコン
    repo: fontawesome/brands/github    # icon:

  # ファビコン
  favicon: assets/python_94570.svg
  # タブ表示を有効.
  features:
    - tabs

plugins:
   - search:
      lang: [ja, en]


# Extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # スーパーフェンス機能の設定
  - pymdownx.superfences
  
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  
  

# CSS
extra_css:
  - "css/custom.css"

# Copyright
copyright: "Copyright © 2021 -  kzrashi All Rights Reserved."


# Customization
extra:
  generator: false

# # Navigation
# nav:
#     - はじめに: index.md
#     - 実行環境: 00_installation.md
#     - 標準出力: 00_print.md
#     - 変数:
#       - 基本            : 01_type/01_00_variable.md
#       - 整数型(int)     : 01_type/01_01_variable_int.md
#       - 小数点型(float) : 01_type/01_02_variable float.md
#       - 真偽型(bool)    : 01_type/01_03_variable bool.md
#       - 文字列型(str)    : 01_type/01_04_variable_str.md
#     - 標準入力: 01_input.md
#     - 演算    : 01_calcurate.md
#     - リスト  : 03_list.md
#     - 辞書:
#       - 表示    : 04_01_dictionary_disp.md
#       - 追加    : 04_02_dictionary_add.md
#       - 削除    : 04_03_dictionary_delete.md
#     - タプル  : 05_tuples.md
#     - 集合    : 06_set.md
#     - if文    : 12_ifStatements.md
#     - 条件式   :  14_condition.md
#     - for文    :  13_forLoops.md
#     - 検索アルゴリズム: 
#       - LinerSearch: 21_algorithm/21_search_algorithm.md
#       - BFS: 21_algorithm/22_tree.md


# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

